# Generated by Django 3.0 on 2021-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(default='images/default_profile_image.png', upload_to='images/'),
        ),
    ]
